KHUgle/urls.py
from django.urls import path
from . import views

app_name = 'KHUgle'         #KHUgle이라는 url 이름을 선언하여 url mapping에 사용한다.

urlpatterns = [
    path('', views.index, name='index'),                      #KHUgle의 인덱스 페이지 --> view로 매핑
    path('<int:post_id>/', views.detail, name='detail'),       #KHUgle의 post detail 페이지
    path('post/create/<path:folder_path>', views.post_create, name='post_create'),
    path('post/modify/<int:post_id>/', views.post_modify, name='post_modify'),
    path('post/delete/<int:post_id>/', views.post_delete, name='post_delete'),
    path('comment/create/<int:post_id>/', views.comment_create, name='comment_create'),
    path('comment/delete/<int:comment_id>/', views.comment_delete, name='comment_delete'),
    path('vote/post/<int:post_id>/', views.vote_post, name='vote_post'),
    path('vote/comment/<int:comment_id>/', views.vote_comment, name='vote_comment'),
    path('post/create/', views.post_create_upper, name='post_create_upper'),
]

KHUgle_drive/urls.py
from django.contrib import admin
from django.urls import path, include
from account.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('driver/', include('driver.urls')),
    path('account/', include('account.urls')),
]

account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from KHUgle import views as KHUgle_views
from . import views

app_name = 'account'

urlpatterns = [
    path('', KHUgle_views.index, name='index'),        #로그인 성공 후 redirect 되는 경로는 KHUgle
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),    #로그인, 로그아웃 경로는 settings.py에 설정
    path('signup/', views.signup, name='signup'),
]

bucket/urls.py
from django.urls import path, include
from . import views

app_name = 'bucket'

urlpatterns = [
    path('private/file', views.private_bucket, name='private_bucket'),
    path('private/file/<path:folder_path>', views.private_bucket_file, name='private_bucket_file'),
    path('private/download/<path:file_path>', views.private_download, name='private_download'),
    path('private/delete/<path:file_path>', views.private_file_delete, name='private_file_delete'),
    path('private/create', views.private_bucket_create, name='private_bucket_create'),
    path('private/create/<path:folder_path>', views.private_folder_create, name='private_folder_create'),
    path('private/download/<path:file_path>', views.private_download, name='private_download'),
    path('private/upload', views.private_upload_file, name='private_upload'),
    path('group/file', views.group_bucket, name='group_bucket'),
    path('group/file/<path:folder_path>', views.group_bucket_file, name='group_bucket_file'),
    path('group/download/<path:file_path>', views.group_download, name='group_download'),
    path('group/delete/<path:file_path>', views.group_file_delete, name='group_file_delete'),
    path('group/log/<path:file_path>', views.group_file_log, name='group_file_log'),
    path('group/create', views.group_bucket_create, name='group_bucket_create'),
    path('group/create/<path:folder_path>', views.group_folder_create, name='group_folder_create'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from KHUgle import views

urlpatterns = [
    path('',views.main, name='main'),                 #초기 페이지인데 새로 만들어줘야한다. Settings의 LOGIN/LOGOUT REDIRECT도 고려
    path('admin/', admin.site.urls),
    path('KHUgle/', include('KHUgle.urls')),
    path('account/', include('account.urls')),
    path('bucket/', include('bucket.urls')),
]

templates/Base/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <title>Hello KHUgle</title>
</head>
<body>
{% include "Base/navbar.html" %}
{% block content %}
{% endblock %}

<script src = "{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src = "{% static 'js/bootstrap.min.js' %}"></script>
<script src = "{% static 'js/jsFile.js' %}"></script>
<script src = "https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>

<!-- JavaScript Start -->

<!-- Google Fonts -->
<link href="https://fonts.googleapis.com/css?family=Merriweather" rel="stylesheet">
{% block script %}
{% endblock %}
<!-- JavaScript End -->

</body>
</html>


<ul class="contextmenu">
    <li><a href="#">삭제</a></li>
    <li><a href="#">로그</a></li>
</ul>

<ul class="contextmenuPrivate">
    <li><a href="#">삭제</a></li>
</ul>

templates/Base/base_plain.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <!--Icon CSS-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">
    <title>Hello KHUgle</title>
</head>
<body>
{% include "Base/navbar_plain.html" %}
{% block content %}
{% endblock %}

<script src = "{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src = "{% static 'js/bootstrap.min.js' %}"></script>

<!-- JavaScript Start -->
{% block script %}
{% endblock %}
<!-- JavaScript End -->

</body>
</html>

templates/Base/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'KHUgle:index' %}">KHUgle</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-between" id="navbarNav">
        <ul class="navbar-nav mr-auto">
            <li>
                <a class="nav-item nav-link" href={% url 'KHUgle:index' %}>COMMUNITY</a>
            </li>
            <li class="nav-item dropdown">
                <a class = "nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    BUCKET
                </a>
                <div class = "dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="nav-link" href={% url 'bucket:private_bucket' %}>PRIVATE BUCKET</a>
                    <a class="nav-link" href={% url 'bucket:group_bucket' %}>GROUP BUCKET</a>
                </div>
            </li>
        </ul>
        <ul class = "navbar-nav">
            <!-- <li class="nav-item"> -->
                {% if user.is_authenticated %}
                <a class="nav-link" href={% url 'account:logout' %}>{{ user.username }} (logout)</a>
                {% else %}
                <a class="nav-link" href={% url 'account:login' %}>LOGIN</a>
                {% endif %}
            <!-- </li> -->
        </ul>
    </div>
</nav>

templates/Base/navbar_plain.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="#">KHUgle</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item ">
                <!-- EMPTY -->
            </li>
        </ul>
    </div>
</nav>