KHUgle/urls.py
from django.urls import path
from . import views

app_name = 'KHUgle'         #KHUgle이라는 url 이름을 선언하여 url mapping에 사용한다.

urlpatterns = [
    path('', views.index, name='index'),                      #KHUgle의 인덱스 페이지 --> view로 매핑
    path('<int:post_id>/', views.detail, name='detail'),       #KHUgle의 post detail 페이지
    path('post/create/<path:folder_path>', views.post_create, name='post_create'),
    path('post/modify/<int:post_id>/', views.post_modify, name='post_modify'),
    path('post/delete/<int:post_id>/', views.post_delete, name='post_delete'),
    path('comment/create/<int:post_id>/', views.comment_create, name='comment_create'),
    path('comment/delete/<int:comment_id>/', views.comment_delete, name='comment_delete'),
    path('vote/post/<int:post_id>/', views.vote_post, name='vote_post'),
    path('vote/comment/<int:comment_id>/', views.vote_comment, name='vote_comment'),
    path('post/create/', views.post_create_upper, name='post_create_upper'),
]

KHUgle_drive/urls.py
from django.contrib import admin
from django.urls import path, include
from account.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('driver/', include('driver.urls')),
    path('account/', include('account.urls')),
]

account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from KHUgle import views as KHUgle_views
from . import views

app_name = 'account'

urlpatterns = [
    path('', KHUgle_views.index, name='index'),        #로그인 성공 후 redirect 되는 경로는 KHUgle
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),    #로그인, 로그아웃 경로는 settings.py에 설정
    path('signup/', views.signup, name='signup'),
]

bucket/urls.py
from django.urls import path, include
from . import views

app_name = 'bucket'

urlpatterns = [
    path('private/file', views.private_bucket, name='private_bucket'),
    path('private/file/<path:folder_path>', views.private_bucket_file, name='private_bucket_file'),
    path('private/download/<path:file_path>', views.private_download, name='private_download'),
    path('private/delete/<path:file_path>', views.private_file_delete, name='private_file_delete'),
    path('private/create', views.private_bucket_create, name='private_bucket_create'),
    path('private/create/<path:folder_path>', views.private_folder_create, name='private_folder_create'),
    path('private/download/<path:file_path>', views.private_download, name='private_download'),
    path('private/upload', views.private_upload_file, name='private_upload'),
    path('group/file', views.group_bucket, name='group_bucket'),
    path('group/file/<path:folder_path>', views.group_bucket_file, name='group_bucket_file'),
    path('group/download/<path:file_path>', views.group_download, name='group_download'),
    path('group/delete/<path:file_path>', views.group_file_delete, name='group_file_delete'),
    path('group/log/<path:file_path>', views.group_file_log, name='group_file_log'),
    path('group/create', views.group_bucket_create, name='group_bucket_create'),
    path('group/create/<path:folder_path>', views.group_folder_create, name='group_folder_create'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from KHUgle import views

urlpatterns = [
    path('',views.main, name='main'),                 #초기 페이지인데 새로 만들어줘야한다. Settings의 LOGIN/LOGOUT REDIRECT도 고려
    path('admin/', admin.site.urls),
    path('KHUgle/', include('KHUgle.urls')),
    path('account/', include('account.urls')),
    path('bucket/', include('bucket.urls')),
]

KHUgle/models.py
from django.db import models
from account.models import CustomUser

# File model을 이용하여 file의 정보를 담는다. (file, filename, filepath)
# Notice model을 이용하여 file name을 기준으로 notice를 정리한다.
# Filelog model을 이용하여 notice와 연결하여 file의 변화 상태를 기록, 보여준다.
# Post model을 이용하여 community 기능을 한다.


# class File(models.Model):
#     file = models.FileField()
#     file_path = models.CharField(max_length=1000)
    
#     def __str__(self):
#         # shell에서 DB확인을 위해 출력 용도로 작성
#         return self.title



# class Notice(models.Model):
#     """Model representing the state of file from S3 bucket"""
#     file_id = models.ForeignKey(File)
    
#     def __str__(self):
#         # shell에서 DB확인을 위해 출력 용도로 작성
#         return self.title
    



# class Filelog(models.Model):
#     """Model representing the log of file from S3 bucket"""
#     notice = models.ForeignKey(Notice, on_delete=models.CASCADE)
#     content = models.TextField()
#     created_at = models.DateTimeField()
    
#     def __str__(self):
#         # shell에서 DB확인을 위해 출력 용도로 작성
#         return self.title

class Post(models.Model):
    """Model representing community posts"""
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE) #커스텀 유저 모델과 연결
    title = models.CharField(max_length=144)
    content = models.TextField()
    file = models.FileField(null=True, upload_to='static/files')
    file_path = models.CharField(max_length=500)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(CustomUser, related_name='voter_post')
    major = models.CharField(max_length=144)# choices=MAJORS

    def __str__(self):
        # shell에서 DB확인을 위해 출력 용도로 작성
        return self.title

class Comment(models.Model):
    """Model representing comment posts"""
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    voter = models.ManyToManyField(CustomUser, related_name='voter_comment')

    

KHUgle/forms.py
from django import forms
from KHUgle.models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'file']

        widgets = {
            'title': forms.TextInput(attrs={'class':'form-control'}),
            'content': forms.Textarea(attrs={'class':'form-control', 'rows':10}),
            'file' : forms.ClearableFileInput(attrs={'multiple': False, 'null':True})
        }

        def __init__(self, *args, **kwargs):
            super(PostForm, self).__init__(*args, **kwargs)
            self.fields['file'].required = False

class DeletePostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'content']

        widgets = {
            'title': forms.TextInput(attrs={'class':'form-control'}),
            'content': forms.Textarea(attrs={'class':'form-control', 'rows':10}),
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            'content': 'comment',
        }

KHUgle/views.py
from .models import Post, Comment
from .forms import PostForm, CommentForm, DeletePostForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.paginator import Paginator
from django.db.models import Q, Count
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
import bucket.s3_work as s3

def main(request):
    """사이트 첫 페이지"""
    return render(request, 'KHUgle/main.html')


@login_required(login_url='account:login')
def index(request):
    """커뮤니티 인덱스 페이지"""
    page = request.GET.get('page', '1')             # 페이지
    kw = request.GET.get('kw', '')                  # 검색어
    so = request.GET.get('so', 'recent')            # 정렬
    post_list = Post.objects.order_by('-created_at')  #post_list는 생성 시간 역순 정렬

    if so == 'recommend':
        post_list = Post.objects.filter(major=request.user.major).annotate(num_voter=Count('voter')).order_by('-num_voter', '-created_at')
    elif so == 'popular':
        post_list = Post.objects.filter(major=request.user.major).annotate(num_comment=Count('comment')).order_by('-num_comment', '-created_at')
    else:
        post_list = Post.objects.filter(major=request.user.major).order_by('-created_at')

    if kw:
        post_list = post_list.filter(
            Q(title__icontains=kw) |
            Q(content__icontains=kw) |
            Q(author__username__icontains=kw) |
            Q(comment__author__username__icontains=kw)
        ).distinct()

    paginator = Paginator(post_list, 10)            # 페이지에 10개씩 묶기
    page_obj = paginator.get_page(page)
    context = {'post_list': page_obj, 'page':page, 'kw':kw, 'so':so}               # page_obj를 불러오기
                                                    # 불러오는 방식 --> localhost:8000/KHUgle/?page=1
    
    return render(request, 'KHUgle/post_list.html', context)   #해당 html를 불러오며 context 전송


@login_required(login_url='account:login')
def detail(request, post_id):
    """커뮤니티에 포스팅 된 글에 접속한 페이지"""
    post = get_object_or_404(Post, pk=post_id)             # DB에서 가져온다.
    context = {'post':post}

    return render(request, 'KHUgle/post_detail.html', context)

@login_required(login_url='account:login')
def post_create_upper(request):
    form = PostForm()
    user = request.user
    bucket_group = 'khugle-drive-testtesttest'

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        filename = str(request.FILES.get('file'))
        if form.is_valid():
            if s3.check_file_exist(bucket_group, '', filename):
                messages.info(request, "이미 존재하는 파일입니다.")
                return redirect('/bucket/group/file')
            post = form.save(commit=False)
            post.author = request.user
            post.created_at = timezone.now()
            post.major = request.user.major
            post.file_path = str(request.FILES.get('file'))
            post.save()
            for file in form.files:
                 s3.upload_file(str(request.FILES.get('file')), bucket_group, filename)
            messages.info(request, "파일이 성공적으로 업로드 되었습니다.")
            return redirect('bucket:group_bucket')
    else:
        form = PostForm()
    context = {'form': form}
    return render(request, 'KHUgle/post_form.html', context)

@login_required(login_url='account:login')
def post_create(request, folder_path):
    form = PostForm()
    user = request.user
    bucket_group = 'khugle-drive-'+user.major.lower()

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        filename = str(request.FILES.get('file'))
        print(filename)
        if form.is_valid():
            if not s3.check_file_exist(bucket_group, folder_path, filename):
                messages.info(request, "이미 존재하는 파일입니다.")
                return redirect('/bucket/group/file/' + folder_path)
            post = form.save(commit=False)
            post.author = request.user
            post.created_at = timezone.now()
            post.major = request.user.major
            post.file_path = folder_path + str(request.FILES.get('file'))
            post.save()
            for file in form.files:
                 s3.upload_file(str(request.FILES.get('file')), bucket_group, folder_path + filename)
            messages.info(request, "파일이 성공적으로 업로드 되었습니다.")
            return redirect('bucket:group_bucket_file', folder_path=folder_path)
    else:
        form = PostForm()
    context = {'form': form}
    return render(request, 'KHUgle/post_form.html', context)


@login_required(login_url='account:login')
def post_modify(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.author:
        messages.error(request, 'Permission Error')
        return redirect('KHUgle:detail', post_id=post.id)

    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.updated_at = timezone.now()  # 수정일시 저장
            post.save()
            return redirect('KHUgle:detail', post_id=post.id)
    else:
        form = PostForm(instance=post)
    context = {'form': form}
    return render(request, 'KHUgle/post_form.html', context)


@login_required(login_url='account:login')
def post_delete(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.author:
        messages.error(request, 'Permission Error')
        return redirect('KHUgle:detail', post_id=post.id)
    post.delete()
    return redirect('KHUgle:index')

@login_required(login_url='account:login')
def comment_create(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if (request.method == "POST"):
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.created_at = timezone.now()
            comment.author = request.user
            comment.save()
            redirect('KHUgle:detail', post_id=post_id)
    else:
        form = CommentForm()
    context = {'post':post, 'form':form}
    return render(request, 'KHUgle/post_detail.html', context)


@login_required(login_url='account:login')
def comment_delete(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if (request.user != comment.author):
        messages.error(request, 'No Permission')
    else:
        comment.delete()
    return redirect('KHUgle:detail', post_id=comment.post.id)


@login_required(login_url='account:login')
def vote_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    post.voter.add(request.user)
    return redirect('KHUgle:detail', post_id=post.id)


@login_required(login_url='account:login')
def vote_comment(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    comment.voter.add(request.user)
    return redirect('KHUgle:detail', post_id=comment.post.id)

@login_required(login_url='account:login')
def post_create_upper(request):
    form = PostForm()
    user = request.user
    bucket_group = 'khugle-drive-'+user.major.lower()

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        filename = str(request.FILES.get('file'))
        if form.is_valid():
            if s3.check_file_exist(bucket_group, '', filename):
                messages.info(request, "이미 존재하는 파일입니다.")
                return redirect('/bucket/group/file')
            post = form.save(commit=False)
            post.author = request.user
            post.created_at = timezone.now()
            post.major = request.user.major
            post.file_path = str(request.FILES.get('file'))
            post.save()
            for file in form.files:
                 s3.upload_file(str(request.FILES.get('file')), bucket_group, filename)
            messages.info(request, "파일이 성공적으로 업로드 되었습니다.")
            return redirect('bucket:group_bucket')
    else:
        form = PostForm()
    context = {'form': form}
    return render(request, 'KHUgle/post_form.html', context)

templates/KHUgle/delete_post_form.html
{% extends 'Base/base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">Delete Post</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        <p>
            <label for="id_title">Title:</label>
            {{ form.title }}
        </p>
        <p>
            <label for="id_content">Content:</label>
            {{ form.content}}
        </p>
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>
{% endblock %}

templates/KHUgle/post_detail.html
{% extends 'Base/base.html' %}
{% block content %}

<!-- {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
{% endif %} -->

<div class="container my-3">
    <h2 class="border-bottom py-2">{{ post.title }}</h2>
    <div class="row my-3">
        <div class="col-1">
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{ post.voter.count }}</div>
            <a href="#" data-uri="{% url 'KHUgle:vote_post' post.id %}" class="recommend btn btn-sm btn-secondary btn-block my-1">♥</a>
        </div>
        <div class="col-11">
            <div class="card my-3">
                <div class="card-body">
                    <div class="card-text" style="white-space: pre-line;">{{ post.content }}</div>
                    <div class="d-flex justify-content-end">
                        <div class="badge badge-light p-2 text-left">
                            <div class="mb-2">{{ post.author.username }}</div>
                            <div>{{ post.created_at }}</div>
                        </div>
                    </div>
                    {% if post.updated_at %}
                    <div class="d-flex justify-content-end">
                        <div class="badge badge-light p-2 text-left">
                            <div class="mb-2">Updated</div>
                            <div>{{ post.updated_at }}</div>
                        </div>
                    </div>
                    {% endif %}
                    {% if request.user == post.author %}
                    <div class="my-3">
                        <a href="{% url 'KHUgle:post_modify' post.id  %}" 
                        class="btn btn-sm btn-outline-secondary">Modify</a>
                        <a href="#" class="delete btn btn-sm btn-outline-secondary"
                        data-uri="{% url 'KHUgle:post_delete' post.id  %}">Delete</a>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    
    <div class="card-body">
        <h5 class="border-bottom my-3 py-2">{{ post.comment_set.count }} Comments</h5>
        {% for comment in post.comment_set.all %}
        <div class="row my-3">
            <div class="col-1">
                <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{ comment.voter.count }}</div>
                <a href="#" data-uri="{% url 'KHUgle:vote_comment' comment.id %}" class="recommend btn btn-sm btn-secondary btn-block my-1">♥</a>
            </div>
            <div class="col-11">
                <div class="card my-3">
                    <div class="card-body">
                        <div class="card-text" style="white-space: pre-line;">{{ comment.content }}</div>
                        <div class="d-flex justify-content-end">
                            <div class="badge badge-light p-2">
                                <div class="mb-2">{{ comment.author.username }}</div>
                                <div>{{ comment.created_at }}</div>
                            </div>
                        </div>
                    </div>
                    {% if request.user == comment.author %}
                    <div class="my-3">
                        <a href="#" class="delete btn btn-sm btn-outline-secondary"
                        data-uri="{% url 'KHUgle:comment_delete' comment.id  %}">Delete</a>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>   
        {% endfor %}

        <form action="{% url 'KHUgle:comment_create' post.id %}" method="post">
            {% csrf_token %}
            {% if form.errors %}
            <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
            {% endfor %}
            </div>
            {% endif %}
            <div class ="form-group">
                <textarea name="content" id="content" class="form-control" rows="10"></textarea>
            </div>
            <input type="submit" value="Leave a comment" class="btn btn-primary">
        </form>
    </>
</div>
{% endblock %}

{% block script %}
<script type='text/javascript'>
    $(document).ready(function(){
        $(".delete").on('click', function() {
            if(confirm("정말로 삭제하시겠습니까?")) {
                location.href = $(this).data('uri');
            }
        });

        $(".recommend").on('click', function() {
            if(confirm("추천하시겠습니까?")) {
                location.href = $(this).data('uri');
            }
        });
    });
    </script>
{% endblock %}

templates/KHUgle/post_form.html
{% extends 'Base/base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">Post</h5>
    <form method="post" class="post-form my-3" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>
{% endblock %}

templates/KHUgle/post_list.html
{% extends 'Base/base.html' %}
{% load KHUgle_filter %}
{% block content %}
<div class="container my-3">
    <p>{{user.major}} Group Board</p>
    <div class="row justify-content-between my-3">
        <div class="col-2">
            <select class="form-control so">
                <option value="recent" {% if so == 'recent' %}selected{% endif %}>Recent</option>
                <option value="recommend" {% if so == 'recommend' %}selected{% endif %}>Recommend</option>
                <option value="popular" {% if so == 'popular' %}selected{% endif %}>Popular</option>
            </select>
        </div>

        <div class="col-3 input-group">
            <input type="text" class="form-control kw" value="{{ kw|default_if_none:'' }}">
            <div class="input-group-append">
                <buttom class="btn btn-outline-secondary" type="button" id="btn_search">Search</buttom>
            </div>
        </div>
    </div>
    
    <table class="table">
        <thead>
        <tr class="text-center thead-dark">
            <th>Number</th>
            <th> ♥ </th>
            <th style="width:30%">Title</th>
            <th class="text-center">File</th>
            <th class="text-left">Author</th>
            <th>Created</th>
        </tr>
        </thead>

        <tbody>
        {% if post_list %}
        {% for post in post_list %}
        <tr class="text-center">
            <td>{{ post_list.paginator.count|sub:post_list.start_index|sub:forloop.counter0|add:1 }}</td>
            <td>
                <span class="badge badge-warning px-2 py-1">{{ post.voter.all.count }}</span>
            </td>
            <td class="text-left">
                <a href="{% url 'KHUgle:detail' post.id %}">{{ post.title }}</a>
                {% if post.comment_set.count > 0 %}
                <span class="text-danger small ml-2">{{ post.comment_set.count }}</span>
                {% endif %}
            </td> 
            <td class="text-class">{{ post.file_path }}</td>
            <td class="text-left">{{ post.author.username }} </td>
            <td class="text-center">{{ post.created_at }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">EMPTY</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    
    <ul class="pagination justify-content-center">
 
        {% if post_list.has_previous %}
        <li class="page-item">
            <!-- <a class="page-link" href="?page={{ post_list.previous_page_number }}">Previous</a> -->
            <a class="page-link" data-page="{{ post_list.previous_page_number }}" href="#">Previous</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">Previous</a>
        </li>
        {% endif %}
      
        {% for page_number in post_list.paginator.page_range %}
        {% if page_number >= post_list.number|add:-5 and page_number <= post_list.number|add:5 %}
            {% if page_number == post_list.number %}
            <li class="page-item active" aria-current="page">
                <!-- <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a> -->
                <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <!-- <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a> -->
                <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if post_list.has_next %}
        <li class="page-item">
            <!-- <a class="page-link" href="?page={{ post_list.next_page_number }}">Next</a> -->
            <a class="page-link" data-page="{{ post_list.next_page_number }}" href="#">Next</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">Next</a>
        </li>
        {% endif %}
    </ul>

</div>
<form id="searchForm" method="get" action="{% url 'KHUgle:index' %}" >
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
    <input type="hidden" id="so" name="so" value="{{ so }}">
</form>
{% endblock %}
{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".page-link").on('click', function() {
        $("#page").val($(this).data("page"));
        $("#searchForm").submit();
    });

    $("#btn_search").on('click', function() {
        $("#kw").val($(".kw").val());
        $("#page").val(1);
        $("#searchForm").submit();
    });

    $(".so").on('change', function() {
        $("#so").val($(this).val());
        $("#page").val(1);
        $("#searchForm").submit();
    });
});
</script>
{% endblock %}

templates/KHUgle/post_log.html
{% extends 'Base/base.html' %}
{% load KHUgle_filter %}
{% block content %}
<div class="container my-3">
    <p>{{user.major}} Group Board</p>
    <p><a href="{% url 'bucket:group_download' file_path %}"> {{ file_path }}</a></p>
    <table class="table">
        <thead>
        <tr class="text-center thead-dark">
            <th>Number</th>
            <th> ♥ </th>
            <th style="width:50%">Title</th>
            <th class="text-left">Author</th>
            <th>Created</th>
        </tr>
        </thead>

        <tbody>
        {% if post_list %}
        {% for post in post_list %}
        <tr class="text-center">
            <td>{{ post_list.paginator.count|sub:post_list.start_index|sub:forloop.counter0|add:1 }}</td>
            <td>
                <span class="badge badge-warning px-2 py-1">{{ post.voter.all.count }}</span>
            </td>
            <td class="text-left">
                <a href="{% url 'KHUgle:detail' post.id %}">{{ post.title }}</a>
                {% if post.comment_set.count > 0 %}
                <span class="text-danger small ml-2">{{ post.comment_set.count }}</span>
                {% endif %}
            </td> 
            <td class="text-left">{{ post.author.username }} </td>
            <td class="text-center">{{ post.created_at }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">EMPTY</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    
    <ul class="pagination justify-content-center">
 
        {% if post_list.has_previous %}
        <li class="page-item">
            <!-- <a class="page-link" href="?page={{ post_list.previous_page_number }}">Previous</a> -->
            <a class="page-link" data-page="{{ post_list.previous_page_number }}" href="#">Previous</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">Previous</a>
        </li>
        {% endif %}
      
        {% for page_number in post_list.paginator.page_range %}
        {% if page_number >= post_list.number|add:-5 and page_number <= post_list.number|add:5 %}
            {% if page_number == post_list.number %}
            <li class="page-item active" aria-current="page">
                <!-- <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a> -->
                <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <!-- <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a> -->
                <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if post_list.has_next %}
        <li class="page-item">
            <!-- <a class="page-link" href="?page={{ post_list.next_page_number }}">Next</a> -->
            <a class="page-link" data-page="{{ post_list.next_page_number }}" href="#">Next</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">Next</a>
        </li>
        {% endif %}
    </ul>

</div>
<form id="searchForm" method="get" action="{% url 'KHUgle:index' %}" >
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
    <input type="hidden" id="so" name="so" value="{{ so }}">
</form>
{% endblock %}
{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".page-link").on('click', function() {
        $("#page").val($(this).data("page"));
        $("#searchForm").submit();
    });

    $("#btn_search").on('click', function() {
        $("#kw").val($(".kw").val());
        $("#page").val(1);
        $("#searchForm").submit();
    });

    $(".so").on('change', function() {
        $("#so").val($(this).val());
        $("#page").val(1);
        $("#searchForm").submit();
    });
});
</script>
{% endblock %}