KHUgle/urls.py
from django.urls import path
from . import views

app_name = 'KHUgle'         #KHUgle이라는 url 이름을 선언하여 url mapping에 사용한다.

urlpatterns = [
    path('', views.index, name='index'),                      #KHUgle의 인덱스 페이지 --> view로 매핑
    path('<int:post_id>/', views.detail, name='detail'),       #KHUgle의 post detail 페이지
    path('post/create/<path:folder_path>', views.post_create, name='post_create'),
    path('post/modify/<int:post_id>/', views.post_modify, name='post_modify'),
    path('post/delete/<int:post_id>/', views.post_delete, name='post_delete'),
    path('comment/create/<int:post_id>/', views.comment_create, name='comment_create'),
    path('comment/delete/<int:comment_id>/', views.comment_delete, name='comment_delete'),
    path('vote/post/<int:post_id>/', views.vote_post, name='vote_post'),
    path('vote/comment/<int:comment_id>/', views.vote_comment, name='vote_comment'),
    path('post/create/', views.post_create_upper, name='post_create_upper'),
]

KHUgle_drive/urls.py
from django.contrib import admin
from django.urls import path, include
from account.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('driver/', include('driver.urls')),
    path('account/', include('account.urls')),
]

bucket/urls.py
from django.urls import path, include
from . import views

app_name = 'bucket'

urlpatterns = [
    path('private/file', views.private_bucket, name='private_bucket'),
    path('private/file/<path:folder_path>', views.private_bucket_file, name='private_bucket_file'),
    path('private/download/<path:file_path>', views.private_download, name='private_download'),
    path('private/delete/<path:file_path>', views.private_file_delete, name='private_file_delete'),
    path('private/create', views.private_bucket_create, name='private_bucket_create'),
    path('private/create/<path:folder_path>', views.private_folder_create, name='private_folder_create'),
    path('private/download/<path:file_path>', views.private_download, name='private_download'),
    path('private/upload', views.private_upload_file, name='private_upload'),
    path('group/file', views.group_bucket, name='group_bucket'),
    path('group/file/<path:folder_path>', views.group_bucket_file, name='group_bucket_file'),
    path('group/download/<path:file_path>', views.group_download, name='group_download'),
    path('group/delete/<path:file_path>', views.group_file_delete, name='group_file_delete'),
    path('group/log/<path:file_path>', views.group_file_log, name='group_file_log'),
    path('group/create', views.group_bucket_create, name='group_bucket_create'),
    path('group/create/<path:folder_path>', views.group_folder_create, name='group_folder_create'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from KHUgle import views

urlpatterns = [
    path('',views.main, name='main'),                 #초기 페이지인데 새로 만들어줘야한다. Settings의 LOGIN/LOGOUT REDIRECT도 고려
    path('admin/', admin.site.urls),
    path('KHUgle/', include('KHUgle.urls')),
    path('account/', include('account.urls')),
    path('bucket/', include('bucket.urls')),
]

bucket/models.py
from django.db import models
from account.models import CustomUser

# Create your models here.
class File(models.Model):
    """Model representing file to upload or download"""
    is_folder = models.BooleanField(default=False)
    file = models.FileField()
    path = models.CharField(max_length=1000)
    user = models.CharField(max_length=100)

bucket/views.py
from KHUgle.models import Post
from django.shortcuts import render
from KHUgle.forms import DeletePostForm
from rest_framework.decorators import action
from rest_framework import viewsets, permissions, renderers
from rest_framework.views import APIView
from rest_framework.decorators import api_view
from django.core.paginator import Paginator
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q, Count
from django.views.decorators.csrf import csrf_exempt
from .models import File
from django.http import JsonResponse
from .serializer import FileSerializer
from django.conf import settings
from django.shortcuts import redirect
from django.utils import timezone
import bucket.s3_work as s3
import os
from django.core.files.storage import FileSystemStorage

# Create your views here.
@csrf_exempt
@login_required(login_url='account:login')
def private_bucket(request):
    permission_classes = (permissions.IsAuthenticated,)
    user = request.user
    bucket_private = 'khugle-drive-' + user.username

    if request.method == 'GET':
        file_list = s3.list_object('khugle-drive-' + user.username, '', user)
        return render(request, 'bucket/private_bucket.html', {'file_list' : file_list})

    if request.method == 'POST':
        try:
            myfile = request.FILES['upload']

            if s3.check_file_exist(bucket_private, '', myfile):
                messages.info(request, "이미 존재하는 파일입니다.")
                return redirect('/bucket/private/file')

            fs = FileSystemStorage("static/files")
            filename = fs.save(myfile.name, myfile)
            print(filename)
            messages.info(request, "성공적으로 파일을 저장했습니다.")
            s3.upload_file(filename, 'khugle-drive-'+request.user.username)
            file_list = s3.list_object('khugle-drive-' + user.username, '', user)
            return render(request, 'bucket/private_bucket.html', {'file_list' : file_list})
        except:
            file_list = s3.list_object('khugle-drive-' + user.username, '', user)
            return render(request, 'bucket/private_bucket.html', {'file_list' : file_list})


@csrf_exempt
@login_required(login_url='account:login')
def private_bucket_file(request, folder_path):
    permission_classes = (permissions.IsAuthenticated,)
    user = request.user
    bucket_private = 'khugle-drive-' + user.username

    if request.method == 'GET':
        folders = folder_path.split('/')
        folder_path = ''
        for i in range(len(folders)-1):
            folder_path += folders[i] + '/'
        file_list = s3.list_object(bucket_private, folder_path, user)
        return render(request, 'bucket/private_bucket_file.html', {'file_list' : file_list, 'current_path' : folder_path})

    if request.method == 'POST':
        try:
            myfile = request.FILES['upload']

            if s3.check_file_exist(bucket_private, folder_path, myfile):
                messages.info(request, "이미 존재하는 파일입니다.")
                return redirect('/bucket/private/file/' + folder_path)

            folders = folder_path.split('/')
            folder_path = ''
            for i in range(len(folders)-1):
                folder_path += folders[i] + '/'
            fs = FileSystemStorage("static/files")
            filename = fs.save(myfile.name, myfile)
            
            s3.upload_file(filename, 'khugle-drive-'+request.user.username, folder_path+filename)
            file_list = s3.list_object('khugle-drive-' + user.username, folder_path, user)
            return render(request, 'bucket/private_bucket_file.html', {'file_list' : file_list, 'current_path' : folder_path})
        except:
            file_list = s3.list_object('khugle-drive-' + user.username, folder_path, user)
            return render(request, 'bucket/private_bucket_file.html', {'file_list' : file_list, 'current_path' : folder_path})

@login_required(login_url='account:login')
def private_download(request, file_path):
    user = request.user
    bucket_private = 'khugle-drive-' + user.username
    print("file_path : "+ file_path)

    if settings.USER_OS == 'Windows':
        download_path = settings.WINDOWS_DOWNLOAD_PATH
    elif settings.USER_OS == "Darwins":
        download_path = settings.MAC_DOWNLOAD_PATH

    folders = file_path.split('/')
    file_name = folders[-1]

    #s3.download_file(bucket_private, file_path, download_path + '/' + file_name)
    res = s3.download_file(bucket_private, file_path, "")
    print(res)
    return redirect(res)
    '''
    if len(folders) == 1:
        return redirect('/bucket/private/file')
    new_path = '/'
    for i in range(len(folders) - 1):
        new_path += folders[i]
        new_path += '/'
    return redirect('/bucket/private/file' + new_path)
    '''

@login_required(login_url='account:login')
def private_file_delete(request, file_path):
    user = request.user
    bucket_private = 'khugle-drive-' + user.username
    #bucket_major = 'khugle-drive-' + user.major.lower()
    print("file_path : "+ file_path)
    s3.delete_file(file_path, bucket_private)
    folders = file_path.split('/')
    if len(folders) == 1:
        return redirect('/bucket/private/file')
    new_path = '/'
    for i in range(len(folders) - 1):
        new_path += folders[i]
        new_path += '/'
    return redirect('/bucket/private/file' + new_path)

@csrf_exempt
@login_required(login_url='account:login')
def private_bucket_create(request):
    user = request.user
    bucket_private = 'khugle-drive-' + user.username
    if request.method == 'POST':
        if not s3.check_folder_exist(bucket_private, "", request.POST['bucket']):   
            print("" + request.POST['bucket'])
            s3.make_directory(request.POST['bucket'], bucket_private, '')
            messages.info(request, '성공적으로 폴더를 생성했습니다.')
        else:
            messages.info(request, '이미 존재하는 폴더입니다.')
    return redirect('/bucket/private/file')


@csrf_exempt
@login_required(login_url='account:login')
def private_folder_create(request, folder_path):
    user = request.user
    bucket_private = 'khugle-drive-' + user.username
    if request.method == 'POST':
        if not s3.check_folder_exist(bucket_private, folder_path, request.POST['folder']):   
            print(folder_path + request.POST['folder'])
            s3.make_directory(folder_path + request.POST['folder'], bucket_private, '')
            messages.info(request, '성공적으로 폴더를 생성했습니다.')
        else:
            messages.info(request, '이미 존재하는 폴더입니다.')
    return redirect('/bucket/private/file/' + folder_path)

@login_required(login_url='account:login')
def group_bucket(request):
    permission_classes = (permissions.IsAuthenticated,)
    user = request.user
    bucket_major = 'khugle-drive-testtesttest'
    #bucket_major = 'khugle-drive-' + user.major.lower()

    if request.method == 'GET':
        file_list = s3.list_object(bucket_major, '', user)
        return render(request, 'bucket/group_bucket.html', {'file_list' : file_list})

@login_required(login_url='account:login')
def group_bucket_file(request, folder_path):
    permission_classes = (permissions.IsAuthenticated,)
    user = request.user
    bucket_major = 'khugle-drive-testtesttest'
    #bucket_major = 'khugle-drive-' + user.major.lower()      
    folders = folder_path.split('/')
    folder_path = ''
    for i in range(len(folders)-1):
        folder_path += folders[i] + '/'
    file_list = s3.list_object(bucket_major, folder_path, user)
    return render(request, 'bucket/group_bucket_file.html', {'file_list' : file_list, 'current_path' : folder_path})

@login_required(login_url='account:login')
def group_download(request, file_path):
    user = request.user
    bucket_major = 'khugle-drive-'+user.major.lower()
    
    print("file_path : "+ file_path)

    #if settings.USER_OS == 'Windows':
    download_path = settings.WINDOWS_DOWNLOAD_PATH
    #elif settings.USER_OS == "Darwins":
    #    download_path = settings.MAC_DOWNLOAD_PATH
    #else:
    #    download_path = settings.UBUNTU_DOWNLOAD_PATH
    folders = file_path.split('/')
    file_name = folders[-1]

    #s3.download_file(bucket_major, file_path, download_path + '/' + file_name)
    res = s3.download_file(bucket_major, file_path, "")
    print(res)
    return redirect(res)
    '''
    folders = file_path.split('/')
    if len(folders) == 1:
        return redirect('/bucket/group/file')
    new_path = '/'
    for i in range(len(folders) - 1):
        new_path += folders[i]
        new_path += '/'
    
    return redirect('/bucket/group/file' + new_path)
    '''
@login_required(login_url='account:login')
def group_file_log(request, file_path):
    """커뮤니티 인덱스 페이지"""
    page = request.GET.get('page', '1')             # 페이지
    # kw = request.GET.get('kw', '')                  # 검색어
    # so = request.GET.get('so', 'recent')            # 정렬
    post_list = Post.objects.filter(file_path=file_path).order_by('-created_at')  #post_list는 생성 시간 역순 정렬
    print(post_list)
    # if so == 'recommend':
    #     post_list = Post.objects.filter(major=request.user.major).annotate(num_voter=Count('voter')).order_by('-num_voter', '-created_at')
    # elif so == 'popular':
    #     post_list = Post.objects.filter(major=request.user.major).annotate(num_comment=Count('comment')).order_by('-num_comment', '-created_at')
    # else:
    #     post_list = Post.objects.filter(major=request.user.major).order_by('-created_at')

    # if kw:
    #     post_list = post_list.filter(
    #         Q(title__icontains=kw) |
    #         Q(content__icontains=kw) |
    #         Q(author__username__icontains=kw) |
    #         Q(comment__author__username__icontains=kw)
    #     ).distinct()

    paginator = Paginator(post_list, 10)            # 페이지에 10개씩 묶기
    page_obj = paginator.get_page(page)
    context = {'post_list': page_obj, 'file_path': file_path, 'page':page}               # page_obj를 불러오기

templates/bucket/group_bucket.html
{% extends 'Base/base.html' %}
{% load static %}
{% block content %}
<script>
    function CreateFolder(){
    var item = $('#cf')
    console.log(item.html())
    item.html("<form action=\"{% url 'bucket:group_bucket_create'%}\" method='POST' style='float:right; margin-left: 5px'>\
        <input type='text' id='bucket' name='bucket'>\
        <input class ='btn btn-primary' type='submit' value='Create'>\
    </form>")
  }          
</script>

<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="thead-dark">
            <th>Folder</th>
        </tr>
        </thead>
    </table>

    <tbody>
    <div class = "grid-5">

    {% if file_list %}
    {% for file in file_list %}
    <!-- <tr class="text-center"> -->
        {% if file.is_folder %}
        <div class ="items"><a href="{% url 'bucket:group_bucket_file' file.path %}"><img src="{% static './img/folder.png' %}"></a>{{ file.name }}</div>
        {% endif %}
    <!-- </tr> -->
    {% endfor %}
    {% else %}
    <tr>
        <td colspan="3">EMPTY</td>
    </tr>
    {% endif %}
    </div>
    </tbody>

    <tbody>
    <table class="table">
        <thead>
        <tr class="thead-dark">
            <th>File</th>
        </tr>
        </thead>
    </table>

    <div class = "grid-5">
    {% if file_list %}
    {% for file in file_list %}
    <!-- <tr class="text-center"> -->
        {% if not file.is_folder %}
        <div class ="items"><a href="{% url 'bucket:group_download' file.path %}"><img src="{% static './img/file.jpg' %}"></a>{{ file.name }}</div>
        {% else %}
        {% endif %}
    <!-- </tr> -->
    {% endfor %}
    {% else %}
    <tr>
        <td colspan="3">EMPTY</td>
    </tr>
    {% endif %}
    </div>

    </tbody>

    <div id = "cf" style="display:inline">
        <button class="btn btn-primary" style="float:right; margin-left: 5px;" onclick="CreateFolder()">Create Folder</button>
    </div>

    <div class="abutton" style="float:right; display:inline">
        <a href="{% url 'KHUgle:post_create_upper' %}" class="btn btn-primary">Post</a>
    </div>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}"{% endif %} style="float:right; margin-left: 5px;" >{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}

</div>
{% endblock %}

templates/bucket/group_bucket_file.html
{% extends 'Base/base.html' %}
{% load bucket_filter %}
{% load static %}
{% block content %}
<script>
    function CreateFolder(){
    var item = $('#cf')
    console.log(item.html())
    item.html("<form action=\"{% url 'bucket:group_folder_create' current_path %}\" method='POST' style='float:right; margin-left: 5px'>\
        <input type='text' id='folder' name='folder'>\
        <input class ='btn btn-primary' type='submit' value='Create'>\
    </form>")
  }          
</script>

<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="thead-dark">
            <th>Folder</th>
        </tr>
        </thead>
    </table>

    <tbody>
    <div class = "grid-5">

    {% if current_path|is_bucket %}
    <div class ="items"><a href="{% url 'bucket:group_bucket' %}"><img src="{% static './img/folder.png' %}"></a>...</div>
    {% else %}
    <div class ="items"><a href="{% url 'bucket:group_bucket_file' current_path|upper_path %}"><img src="{% static './img/folder.png' %}"></a>...</div>
    {% endif %}

    {% if file_list %}
    {% for file in file_list %}
    <!-- <tr class="text-center"> -->
        {% if file.is_folder %}
        <div class ="items"><a href="{% url 'bucket:group_bucket_file' file.path %}"><img src="{% static './img/folder.png' %}"></a>{{ file.name }}</div>
        {% endif %}
    <!-- </tr> -->
    {% endfor %}
    {% else %}
    <tr>
        <td colspan="3">EMPTY</td>
    </tr>
    {% endif %}
    </div>
    </tbody>

    <tbody>
    <table class="table">
        <thead>
        <tr class="thead-dark">
            <th>File</th>
        </tr>
        </thead>
    </table>

    <div class = "grid-5">
    {% if file_list %}
    {% for file in file_list %}
    <!-- <tr class="text-center"> -->
        {% if not file.is_folder %}
        <div class ="items"><a href="{% url 'bucket:group_download' file.path %}"><img src="{% static './img/file.jpg' %}"></a>{{ file.name }}</div>
        {% endif %}
    <!-- </tr> -->
    {% endfor %}
    {% else %}
    <tr>
        <td colspan="3">EMPTY</td>
    </tr>
    {% endif %}
    </div>

    </tbody>
    
    <div id = "cf" style="display:inline">
        <button class="btn btn-primary" style="float:right; margin-left: 5px;" onclick="CreateFolder()">Create Folder</button>
    </div>

    <div class="abutton" style="float:right; display:inline">
        <a href="{% url 'KHUgle:post_create' current_path %}" class="btn btn-primary">Post</a>
    </div>
</div>
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}"{% endif %} style="float:right; margin-left: 5px;" >{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
{% endblock %}

templates/bucket/private_bucket.html
{% extends 'Base/base.html' %}
{% load static %}
{% block content %}
<script>
    function CreateFolder(){
    var item = $('#cf')
    console.log(item.html())
    item.html("<form action=\"{% url 'bucket:private_bucket_create'%}\" method='POST' style='float:right; margin-left: 5px'>\
        <input type='text' id='bucket' name='bucket'>\
        <input class ='btn btn-primary' type='submit' value='Create'>\
    </form>")
  }          
</script>

<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="thead-dark">
            <th>Folder</th>
        </tr>
        </thead>
    </table>

    <tbody>
    <div class = "grid-5">

    {% if file_list %}
    {% for file in file_list %}
    <!-- <tr class="text-center"> -->
        {% if file.is_folder %}
        <div class ="itemsPrivate"><a href="{% url 'bucket:private_bucket_file' file.path %}"><img src="{% static './img/folder.png' %}"></a>{{ file.name }}</div>
        {% endif %}
    <!-- </tr> -->
    {% endfor %}
    {% else %}
    <tr>
        <td colspan="3">EMPTY</td>
    </tr>
    {% endif %}
    </div>
    </tbody>

    <tbody>
    <table class="table">
        <thead>
        <tr class="thead-dark">
            <th>File</th>
        </tr>
        </thead>
    </table>

    <div class = "grid-5">
    {% if file_list %}
    {% for file in file_list %}
    <!-- <tr class="text-center"> -->
        {% if not file.is_folder %}
        <div class ="itemsPrivate"><a href="{% url 'bucket:private_download' file.path %}"><img src="{% static './img/file.jpg' %}"></a>{{ file.name }}</div>
        {% endif %}
    <!-- </tr> -->
    {% endfor %}
    {% else %}
    <tr>
        <td colspan="3">EMPTY</td>
    </tr>
    {% endif %}
    </div>

    </tbody>

    

    <form method='POST' style="display:inline"  enctype="multipart/form-data">
        <div class="file-droppable" style="display:block">
            <div>Drag and drop file here</div>
            <span>&times;</span>
            <input type="file" name="upload" />
        </div>
        <input class = "btn btn-primary" type="submit" value="Upload" style="vertical-align: middle"/>
    </form>

    <div id = "cf" style="display:inline">
        <button class="btn btn-primary" style="float:right;" onclick="CreateFolder()">Create Folder</button>
    </div>

    <!-- <div class="abutton" style="float:right; display:inline">
        <a href="" class="btn btn-primary">Post</a>
    </div> -->
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}"{% endif %} style="float:right; margin-left: 5px;" >{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}

</div>
{% endblock %}

templates/bucket/private_bucket_file.html
{% extends 'Base/base.html' %}
{% load bucket_filter %}
{% load static %}
{% block content %}
<script>
    function CreateFolder(){
    var item = $('#cf')
    console.log(item.html())
    item.html("<form action=\"{% url 'bucket:private_folder_create' current_path %}\" method='POST' style='float:right; margin-left: 5px'>\
        <input type='text' id='folder' name='folder'>\
        <input class ='btn btn-primary' type='submit' value='Create'>\
    </form>")
  }          
</script>

<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="thead-dark">
            <th>Folder</th>
        </tr>
        </thead>
    </table>

    <tbody>
    <div class = "grid-5">

    {% if current_path|is_bucket %}
    <div class ="itemsPrivate"><a href="{% url 'bucket:private_bucket' %}"><img src="{% static './img/folder.png' %}"></a>...</div>
    {% else %}
    <div class ="itemsPrivate"><a href="{% url 'bucket:private_bucket_file' current_path|upper_path %}"><img src="{% static './img/folder.png' %}"></a>...</div>
    {% endif %}

    {% if file_list %}
    {% for file in file_list %}
    <!-- <tr class="text-center"> -->
        {% if file.is_folder %}
        <div class ="itemsPrivate"><a href="{% url 'bucket:private_bucket_file' file.path %}"><img src="{% static './img/folder.png' %}"></a>{{ file.name }}</div>
        {% endif %}
    <!-- </tr> -->
    {% endfor %}
    {% else %}
    <tr>
        <td colspan="3">EMPTY</td>
    </tr>
    {% endif %}
    </div>
    </tbody>

    <tbody>
    <table class="table">
        <thead>
        <tr class="thead-dark">
            <th>File</th>
        </tr>
        </thead>
    </table>

    <div class = "grid-5">
    {% if file_list %}
    {% for file in file_list %}
    <!-- <tr class="text-center"> -->
        {% if not file.is_folder %}
        <div class ="itemsPrivate"><a href="{% url 'bucket:private_download' file.path %}"><img src="{% static './img/file.jpg' %}"></a>{{ file.name }}</div>
        {% endif %}
    <!-- </tr> -->
    {% endfor %}
    {% else %}
    <tr>
        <td colspan="3">EMPTY</td>
    </tr>
    {% endif %}
    </div>

    </tbody>

    <form method='POST' style="display:inline"  enctype="multipart/form-data">
        <div class="file-droppable" style="display:block">
            <div>Drag and drop file here</div>
            <span>&times;</span>
            <input type="file" name="upload" />
        </div>
        <input class = "btn btn-primary" type="submit" value="Upload" style="vertical-align: middle"/>
    </form>

    <div id = "cf" style="display:inline">
        <button class="btn btn-primary" style="float:right; margin-left: 5px;" onclick="CreateFolder()">Create Folder</button>
    </div>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}"{% endif %} style="float:right; margin-left: 5px;" >{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
</div>
{% endblock %}

templates/bucket/temp.html
<td class="text-left"><a href="{% url 'bucket:private_bucket_file' file.name %}">{{ file.name }}</a></td>
<td class="text-right"> </td>
<td class="text-right">folder</td>

{% else %}
<td class="text-left"><a href="{% url 'bucket:private_bucket' %}">{{ file.name }}</a></td>
<td class="text-right">{{ file.user }}</td>
<td class="text-right">file</td>

{% extends 'Base/base.html' %}
{% load static %}
{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="thead-dark">
            <th>Bucket</th>
            <th>Uploader</th>
            <th>type</th>
        </tr>
        </thead>

        <tbody>
        {% if file_list %}
        {% for file in file_list %}
        <tr class="text-center">
            {% if file.is_folder %}
            <td class="text-left"><a href="{% url 'bucket:private_bucket' file.name %}">{{ file.name }}</a></td>
            <td class="text-right"> </td>
            <td class="text-right">folder</td>
            {% else %}
            <td class="text-left"><a href="{% url 'bucket:private_bucket' %}">{{ file.name }}</a></td>
            <td class="text-right">{{ file.user }}</td>
            <td class="text-right">file</td>
            {% endif %}
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">EMPTY</td>
        </tr>
        {% endif %}
        </tbody>
    </table>

    <a href="{% url 'bucket:private_bucket'%}" class="btn btn-primary">Post</a>
</div>
{% endblock %}

<div class ="items"><a href="{% url 'bucket:private_bucket_file' file.name %}"><img src="{% static './img/folder.png' %}"></a>{{ file.name }}</div>